main: net.redstoneore.freshwilderness.FreshWilderness
name: FreshWilderness
version: 1.5.0
website: http://redstoneore.net/freshwilderness
authors: [ MarkehMe ]
description: §eFresh Wilderness keeps your wilderness fresh.§aMarkehMe §eis the lead programmer. See §bhttp://redstoneore.net/freshwilderness§e for more information.
softdepend: [ FactionsFramework, Kingdoms, Landlord, Townships, Towny, WorldGuard ]
